version: "3.7"

services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: .
      args:
        - TOKEN
        - USERNAME=pmanko
    volumes:
      - ~/.m2:/root/.m2
